format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$dart$dotnet$golang$nodejs$php$python$rust$ruby$swift\
$cmd_duration $jobs $status $time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "yellow"
format ="[ $path ]($style)"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = "[ $user ]($style)"
style_user = "bold blue"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = " [$hostname]($style) in "
style = "bold red"
trim_at = "-"
ssh_only = true
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = " "

[dart]
symbol = " "

[dotnet]
format = '[$symbol($version )(🎯 $tfm )]($style)'
symbol = '🥅 '
style = 'blue'
heuristic = false

[golang]
symbol = " "

[java]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "
format = '[$symbol$version](147 bold)'

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
