#Font settings
font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  bold:
    family: "FiraCode Nerd Font"
    style: Bold
  italic:
    family: "FiraCode Nerd Font"
    style: Italic
  bold_italic:
    family: "FiraCode Nerd Font"
    style: Bold Italic
  size: 11

alt_send_esc: false
#Window settings
window:
  opacity: 0.95
  padding:
    x: 10
    y: 10
  decorations: buttonless
  dynamic_padding: false
  dimensions:
    columns: 130
    lines: 45

scrolling:
  history: 3000
  multiplier: 3

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: R, mods: Command, chars: "\x1bR" }
